version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: medisync-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "root"
      MSSQL_PID: "Express"
    volumes:
      - db_data:/var/opt/mssql

  appointment-service:
    restart: always
    image: appointment-service:latest
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      MSSQL_DATABASE: master
      MSSQL_ROOT_PASSWORD: root@Parrot
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - db

volumes:
  db_data: