version: '3.8'
services:
  appointment-service:
    restart: always
    image: appointment-service:latest
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://it21219320:Ja0QFW6NGaNdGdAm@medisync.2tgw8b5.mongodb.net/?retryWrites=true&w=majority&appName=MediSync
      CORS_ORIGIN: http://localhost:3000