version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: medisync-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "root"
      MSSQL_PID: "Express"
    volumes:
      - db_data:/var/opt/mssql

  appointment-service:
    restart: always
    image: huntrix007/appointment-service:1.0
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: