name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t huntrix007/appointment-service:latest .
      
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u huntrix007 --password-stdin
      
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag huntrix007/appointment-service huntrix007/appointment-service:${{ github.sha }}
        docker push huntrix007/appointment-service:${{ github.sha }}
        docker push huntrix007/appointment-service:latest