name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t appointment-service:latest .
      
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      # run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u huntrix007 --password-stdin
      run: echo "${{ secrets.ECR_TOKEN }}" | docker login --username AWS --password-stdin 575108922870.dkr.ecr.us-east-1.amazonaws.com
      
    # - name: Push to Docker Hub
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     docker tag huntrix007/appointment-service huntrix007/appointment-service:${{ github.sha }}
    #     docker push huntrix007/appointment-service:${{ github.sha }}
    #     docker push huntrix007/appointment-service:latest
    - name: Push to AWS ECR
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag appointment-service:latest 575108922870.dkr.ecr.us-east-1.amazonaws.com/appointment-service:latest
        docker push 575108922870.dkr.ecr.us-east-1.amazonaws.com/appointment-service:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: MediSyncCluster
        service: appointment
        image: "575108922870.dkr.ecr.us-east-1.amazonaws.com/appointment-service:latest"
        wait-for-service-stability: true